name: mobiplus_authentication_example
description: Demonstrates how to use the mobiplus_authentication_example plugin.

publish_to: 'none'

version: 0.4.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  firebase: ^9.0.2
  firebase_core: ^1.10.5
  firebase_database: ^9.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobiplus_authentication_flutter:
    path: ../

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/mobiplus_logo.png
