name: mobiplus_authentication_flutter
description: A new Flutter project.
publish_to: 'none'

version: 0.4.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  firebase: ^9.0.2
  firebase_core: ^1.10.5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.5
  google_sign_in: 5.0.7
  provider: ^5.0.0
  motion_toast: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/mobiplus_logo.png